### ISSUE TITLE
Failures in memcheck

### ISSUE THREAD

**Issue by paulfloyd** [paulfloyd/freebsdarm64_valgrind#2]
**memcheck/tests/descr_belowsp             (stderr)**

OK needs sudo sysctl security.bsd.stack_guard_page=0
because of double kernel and pthread stack guard pages

**memcheck/tests/freebsd/supponlyobj       (stderr)**

A couple more Conditional jump or moves.

**memcheck/tests/manuel1                   (stderr)**

Testcase is flaky with a variable number of errors in libc.

**memcheck/tests/supp_unknown**

Valgrind is seeing less in the callstack. That means that the suppression file doesn't work. And there's no source line for the guest crash.

**memcheck/tests/suppvarinfo5              (stderr)**

One extra error

**memcheck/tests/varinfo5                  (stderr)**

Lots missing

**Comment by paulfloyd** [comment]
varinfo5 looks very bad

If I debug it with vgdb then I really see nothing when loading the shared lib varinfo5so.so

In main here

│B+>     5    varinfo5_main();                                                 │

(gdb) p $pc
$1 = (void (*)()) 0x21067c <main+8>

I can't step into the function. When I step gdb traps at the one and only error that it sees from a client request.

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x00000000048f1bf0 in ?? ()
(gdb) bt
#0  0x00000000048f1bf0 in ?? ()
#1  0x00000000048f1c90 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

According to procstat

  998           0x210000           0x211000 r-x    1    3   4   2 CN--- vn /home/paulf/scratch/valgrind/memcheck/tests/varinfo5

So the PC for main was OK.

  998          0x48f1000          0x48f2000 r-x    1    5   4   2 CN--- vn /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so

The PC for the break is OK. Why no callstack extending past the so boundary? (Unless the compiler is up to tricks). Why no debuginfo? And why no more errors?

aspacem mapping
```
--1014:1: aspacem (0,4,7) /home/paulf/scratch/valgrind/memcheck/memcheck-arm64-freebsd
--1014:1: aspacem (1,69,7) /home/paulf/scratch/valgrind/memcheck/tests/varinfo5
--1014:1: aspacem (2,126,7) /libexec/ld-elf.so.1
--1014:1: aspacem (3,151,1) /tmp/vgdb-pipe-shared-mem-vgdb-1014-by-paulf-on-???
--1014:1: aspacem (4,207,8) /home/paulf/scratch/valgrind/coregrind/vgpreload_core-arm64-freebsd.so
--1014:1: aspacem (5,282,15) /home/paulf/scratch/valgrind/memcheck/tests
--1014:1: aspacem (6,330,8) /home/paulf/scratch/valgrind/memcheck/vgpreload_memcheck-arm64-freebsd.so
--1014:1: aspacem (7,408,8) /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so
--1014:1: aspacem (8,470,9) /lib/libc.so.7
...
--1014:1: aspacem  34: file 00048e0000-00048e0fff    4096 rw--- d=0x05e i=4090919 o=69632   (6,330)
--1014:1: aspacem  35: file 00048e1000-00048e1fff    4096 r---- d=0x05e i=4094777 o=0       (7,408)
--1014:1: aspacem  36: file 00048e2000-00048f0fff   61440 ----- d=0x000 i=0       o=4096    (5,282)
--1014:1: aspacem  37: file 00048f1000-00048f1fff    4096 r-xT- d=0x05e i=4094777 o=0       (7,408)
--1014:1: aspacem  38: file 00048f2000-0004900fff   61440 ----- d=0x000 i=0       o=69632   (5,282)
--1014:1: aspacem  39: file 0004901000-0004902fff    8192 r---- d=0x05e i=4094777 o=0       (7,408)
--1014:1: aspacem  40: file 0004903000-0004911fff   61440 ----- d=0x000 i=0       o=139264  (5,282)
--1014:1: aspacem  41: file 0004912000-0004912fff    4096 rw--- d=0x05e i=4094777 o=4096    (7,408)
```

What is that --1014:1: aspacem (5,282,15) /home/paulf/scratch/valgrind/memcheck/tests mapping ? anon is mapped as a directory?

I don't show it above but the main PC is right. So is the shared lib.

--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 1 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x20fa0 p_offset 4000, p_filesz 512
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 2 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x311a0 p_offset 4512, p_filesz 112
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 1 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x20fa0 p_offset 4000, p_filesz 512
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 2 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x311a0 p_offset 4512, p_filesz 112
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 1 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x20fa0 p_offset 4000, p_filesz 512
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 2 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x311a0 p_offset 4512, p_filesz 112
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 1 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x20fa0 p_offset 4000, p_filesz 512
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 2 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x311a0 p_offset 4512, p_filesz 112
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 1 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x20fa0 p_offset 4000, p_filesz 512
--1022-- check_elf_and_get_rw_loads: ++*rw_load_count to 2 for /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so p_vaddr 0x311a0 p_offset 4512, p_filesz 112
--1022-- Reading syms from /home/paulf/scratch/valgrind/memcheck/tests/varinfo5so.so


Looks OK ish

raw symbol [  27]: LOC FUN : svma 0x0000010c6c, sz  152  varinfo1_main
    rec(t) [  27]:            val 0x00048f1c6c, sz  152  varinfo1_main
raw symbol [  28]: LOC FUN : svma 0x0000010d04, sz   20  varinfo2_main
    rec(t) [  28]:            val 0x00048f1d04, sz   20  varinfo2_main
raw symbol [  29]: LOC FUN : svma 0x0000010d18, sz   20  varinfo3_main
    rec(t) [  29]:            val 0x00048f1d18, sz   20  varinfo3_main
raw symbol [  30]: LOC FUN : svma 0x0000010d2c, sz   60  varinfo4_main
    rec(t) [  30]:            val 0x00048f1d2c, sz   60  varinfo4_main
raw symbol [  31]: LOC FUN : svma 0x0000010d68, sz   76  foo2
    rec(t) [  31]:            val 0x00048f1d68, sz   76  foo2
raw symbol [  32]: LOC FUN : svma 0x0000010db4, sz  108  foo3
    rec(t) [  32]:            val 0x00048f1db4, sz  108  foo3
raw symbol [  33]: LOC FUN : svma 0x0000010e68, sz  116  blah4
    rec(t) [  33]:            val 0x00048f1e68, sz  116  blah4
raw symbol [  34]: LOC OBJ : svma 0x0000031248, sz   10  static_global_def
    rec(d) [  34]:            val 0x0004912248, sz   10  static_global_def
raw symbol [  35]: LOC OBJ : svma 0x0000031252, sz   10  static_global_undef
    rec(d) [  35]:            val 0x0004912252, sz   10  static_global_undef


Looks like the DWARF gets read OK


Tried gcc and it passes. Hmm.

In fact just relinking with gcc is enough.


with clang / ldl..d

```
objdump -p varinfo5so.so

varinfo5so.so:  file format elf64-littleaarch64

Program Header:
    PHDR off    0x0000000000000040 vaddr 0x0000000000000040 paddr 0x0000000000000040 align 2**3
         filesz 0x0000000000000230 memsz 0x0000000000000230 flags r--
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**16
         filesz 0x0000000000000b18 memsz 0x0000000000000b18 flags r--
    LOAD off    0x0000000000000b18 vaddr 0x0000000000010b18 paddr 0x0000000000010b18 align 2**16
         filesz 0x0000000000000488 memsz 0x0000000000000488 flags r-x
    LOAD off    0x0000000000000fa0 vaddr 0x0000000000020fa0 paddr 0x0000000000020fa0 align 2**16
         filesz 0x0000000000000200 memsz 0x0000000000000200 flags rw-
    LOAD off    0x00000000000011a0 vaddr 0x00000000000311a0 paddr 0x00000000000311a0 align 2**16
         filesz 0x0000000000000070 memsz 0x00000000000000bc flags rw-
 DYNAMIC off    0x0000000000000fb8 vaddr 0x0000000000020fb8 paddr 0x0000000000020fb8 align 2**3
         filesz 0x00000000000001a0 memsz 0x00000000000001a0 flags rw-
   RELRO off    0x0000000000000fa0 vaddr 0x0000000000020fa0 paddr 0x0000000000020fa0 align 2**0
         filesz 0x0000000000000200 memsz 0x0000000000001060 flags r--
EH_FRAME off    0x0000000000000890 vaddr 0x0000000000000890 paddr 0x0000000000000890 align 2**2
         filesz 0x000000000000006c memsz 0x000000000000006c flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**64
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
    NOTE off    0x0000000000000270 vaddr 0x0000000000000270 paddr 0x0000000000000270 align 2**2
         filesz 0x0000000000000018 memsz 0x0000000000000018 flags r--

Dynamic Section:
  NEEDED       libc.so.7
  SONAME       varinfo5so.so
  RELA         0x0000000000000670
  RELASZ       0x0000000000000120
  RELAENT      0x0000000000000018
  RELACOUNT    0x0000000000000003
  JMPREL       0x0000000000000790
  PLTRELSZ     0x00000000000000c0
  PLTGOT       0x00000000000311b8
  PLTREL       0x0000000000000007
  SYMTAB       0x0000000000000288
  SYMENT       0x0000000000000018
  STRTAB       0x0000000000000588
  STRSZ        0x00000000000000e7
  GNU_HASH     0x0000000000000498
  HASH         0x00000000000004e8
  INIT_ARRAY   0x0000000000020fa8
  INIT_ARRAYSZ 0x0000000000000008
  FINI_ARRAY   0x0000000000020fb0
  FINI_ARRAYSZ 0x0000000000000008
  INIT         0x0000000000010ee0
  FINI         0x0000000000010ef0
  VERSYM       0x0000000000000450
  VERNEED      0x0000000000000478
  VERNEEDNUM   0x0000000000000001

Version References:
  required from libc.so.7:
    0x077a28b0 0x00 02 FBSD_1.0

```

and with gcc ld bfd

```
objdump -p varinfo5so.so

varinfo5so.so:  file format elf64-littleaarch64

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**16
         filesz 0x0000000000000f68 memsz 0x0000000000000f68 flags r-x
    LOAD off    0x0000000000001000 vaddr 0x0000000000011000 paddr 0x0000000000011000 align 2**16
         filesz 0x000000000000029e memsz 0x00000000000002f0 flags rw-
 DYNAMIC off    0x0000000000001010 vaddr 0x0000000000011010 paddr 0x0000000000011010 align 2**3
         filesz 0x00000000000001d0 memsz 0x00000000000001d0 flags rw-
    NOTE off    0x0000000000000f50 vaddr 0x0000000000000f50 paddr 0x0000000000000f50 align 2**2
         filesz 0x0000000000000018 memsz 0x0000000000000018 flags r--
EH_FRAME off    0x0000000000000ca0 vaddr 0x0000000000000ca0 paddr 0x0000000000000ca0 align 2**2
         filesz 0x000000000000007c memsz 0x000000000000007c flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-

Dynamic Section:
  NEEDED       libc.so.7
  SONAME       varinfo5so.so
  INIT         0x0000000000000780
  FINI         0x0000000000000c50
  INIT_ARRAY   0x0000000000011000
  INIT_ARRAYSZ 0x0000000000000008
  FINI_ARRAY   0x0000000000011008
  FINI_ARRAYSZ 0x0000000000000008
  HASH         0x0000000000000190
  STRTAB       0x0000000000000448
  SYMTAB       0x0000000000000238
  STRSZ        0x0000000000000109
  SYMENT       0x0000000000000018
  PLTGOT       0x0000000000011238
  PLTRELSZ     0x00000000000000a8
  PLTREL       0x0000000000000007
  JMPREL       0x00000000000006d8
  RELA         0x00000000000005a0
  RELASZ       0x0000000000000138
  RELAENT      0x0000000000000018
  VERNEED      0x0000000000000580
  VERNEEDNUM   0x0000000000000001
  VERSYM       0x0000000000000552
  RELACOUNT    0x0000000000000003

Version References:
  required from libc.so.7:
    0x077a28b0 0x00 02 FBSD_1.0
```

Why should linking make a difference????

At the most I should see the same errors but without debuginfo.

Next: vgdb.

**Comment by paulfloyd** [comment]
The varinfo5 problem is a duplicate of #12

**Comment by paulfloyd** [comment]
The major issues are all fixed.
